In [2]:
import numpy as np
import pandas as pd
'''
MXNet (全称:Apache MXNet) 是一个开源的、灵活且高效的深度学习框架。它由分布式机器学习项目孵化而来, 现为Apache基金会的顶级项目之一。MXNet 主要用于构建、训练和部署深度神经网络。
在 MXNet 框架中, npx 是 mxnet.numpy_extension 的缩写，主要用于扩展和补充 NumPy 接口的一些操作，同时提供了一些 MXNet 特有的运算操作
'''

x = np.array(3.0)
y = np.array(2.0)

x + y, x * y, x / y, x ** y

(5.0, 6.0, 1.5, 9.0)

In [3]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
# 这里是降维求和 得到的都是一个一维张量
a = A.sum(axis=0)
b = A.sum(axis=1)
a, b, a.shape, b.shape


(array([40, 45, 50, 55]), array([ 6, 22, 38, 54, 70]), (4,), (5,))

In [6]:
A.sum(axis=1, keepdims=True) # 这里保持维度不变 得到的是一个二维张量

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [10]:
#点积（Dot Product） 一般指两个向量对应元素相乘后再求和
# (1, 4) @ (4, ) = (1, )
x = np.arange(4).reshape(1, 4)
y = np.ones(4)
x.shape, y.shape, x @ y

((1, 4), (4,), array([6.]))

In [11]:
# 点乘（elementwise multiplication，Hadamard积/对应元素相乘）
# 两个shape相同的矩阵对应元素相乘
x = np.arange(6).reshape(2, 3)
y = np.arange(6).reshape(2, 3)
x, y, x * y

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 0,  1,  4],
        [ 9, 16, 25]]))

In [13]:
# L1范数（曼哈顿范数，Manhattan norm） L1范数是向量中所有元素绝对值之和。 
# L2范数（欧几里得范数，Euclidean norm）
x = np.array([3, -4, 5])
l1 = np.linalg.norm(x, ord=1)  # L1范数 |x1| + |x2| + |x3|
l2 = np.linalg.norm(x, ord=2)  # L2范数 sqrt(x1^2 + x2^2 + x3^2)
l1, l2

(12.0, 7.0710678118654755)

Lp范数
$$ \|x\|_p = \left( \sum_{i=1}^n |x_i|^p \right)^{1/p} $$





